### ISSUE TITLE
Objective minimize_markers_displacement with ACADOS 

### ISSUE THREAD

**Issue by EveCharbie** [pyomeca/bioptim#185]
Error message says there are free variables at the fist node (at least that's how I interpret it).
I guess the problem is that the Lagrange term must be on the entire interval (N points to sum), but finite difference give N-1 points.
Minimize_marker_velocity works fine, so it would be possible to 'fix' the problem by introducing the coordinates_system_idx option in this function Minimize_marker_velocity (to do so I still miss the RT velocity though :( )

**Comment by fbailly** [comment]
As of now, any cost of the type "finite difference", i.e. the expression of which explicitly depends on state variables at several shooting nodes, is not possible with acados. 
It would require a reformulation of the problem in order to be compatible (essentially, augment the state vector and control the derivative of the quantity you wish to minimize)

**Comment by pariterre** [comment]
Can we raise an error when this is detected?

**Comment by pariterre** [comment]
It now raises error, and I don't see any time soon where we implement this for ACADOS
Closing the issue
