### ISSUE TITLE
Auto scaling of optimization variables based on bounds

### ISSUE THREAD

**Issue by fbailly** [pyomeca/bioptim#305]
This feature should help convergence for some ill-conditioned problems (e.g.  several orders of magnitudes between optimization variables)

**Comment by pariterre** [comment]
Some of it is in #307

**Comment by pariterre** [comment]
Is this done?

**Comment by fbailly** [comment]
Not yet ! It also concerns the state and controls.

**Comment by EveCharbie** [comment]
1. @pariterre do you see this issue as complicated? If not, I think I and/or @julo0 will have a look at it in a near future since it is linked to issue #306.
2. Do we really want to scale based on the bounds? Sometimes we put too large bounds just to make sure we do not miss something. Scaling on the initial guess does not seem a good idea either since we often put zero. I think the user should provide the scaling magnitude based on his knowledge of the problem. In that case, it would not be a default behaviour to scale de variables, is it a problem for you?
3. @fbailly I was looking for a smarter way to scale the variables inspired from the preconditioning of the objective as in section 2.2 from https://uwspace.uwaterloo.ca/bitstream/handle/10012/12559/Howse_Alexander.pdf (source added for completeness, but you do not have to read to answer me). I know that it is intended to be computed at each iteration, but could we use something similar to make our change of variables before the problem starts? The goal is to get a better conditioning number and improve convergence better than solely with x10^a scaling as exemplified here https://www.youtube.com/watch?v=3wh_TLzuiRI at 6:00. I would like to have you thought on that topic because I am afraid to distort the problem and give a preferential treatment to the solution expected by the user.

**Comment by pariterre** [comment]
@EveCharbie 

1. It is not complicated per se, but it impacts in subtle ways many places. Therefore, good pre-work thinking must be done so we do it in an efficient and almost self-implementing way (in order to make sure noone forget to do what is supposed to do when implementing new objectives or constraints, for instance). So, yep, it can be done by this developper, but we should all meet beforehand

2. I agree with you. Default behavior should not change what we have right now.
