### ISSUE TITLE
Trouble with online optimization with a trivial slider example.

### ISSUE THREAD

**Issue by Ipuch** [pyomeca/bioptim#337]
I've implemented a simple slider example to get to know the librairy however online optimization doesn't show the graphs and makes the bioviz crash after.

[Here](https://github.com/Ipuch/bioptim/tree/Issue_on_online_optim/examples/Issue_on_online_optim) are the files and find below the error message.

![Capture d’écran de 2021-05-14 16-56-28](https://user-images.githubusercontent.com/40755537/118289187-5f030800-b4d5-11eb-8c51-d9e8f7462e40.png)

```
EXIT: Optimal Solution Found.
      nlpsol  :   t_proc      (avg)   t_wall      (avg)    n_eval
callback_fun  |   1.51ms (100.40us)   1.43ms ( 95.07us)        15
       nlp_f  | 191.00us ( 12.73us) 188.84us ( 12.59us)        15
       nlp_g  |   4.76ms (317.60us)   4.76ms (317.22us)        15
  nlp_grad_f  | 322.00us ( 20.13us) 321.89us ( 20.12us)        16
  nlp_hess_l  |  25.12ms (  1.79ms)  25.07ms (  1.79ms)        14
   nlp_jac_g  |  22.53ms (  1.41ms)  22.48ms (  1.41ms)        16
       total  | 111.43ms (111.43ms) 110.66ms (110.66ms)         1
The X11 connection broke: No error (code 0)
XIO:  fatal IO error 22 (Invalid argument) on X server ":1"
      after 593 requests (593 known processed) with 0 events remaining.
```

**Comment by pariterre** [comment]
Hi @Ipuch 
This bug is none and not caused by bioviz, but by PyQt. It is not possible to solve.
You cannot debug and then launch a PyQt window (in this case bioviz). If you want to debug something, you must call bioviz before any debugger stopper. This is because your computer is probably setup in french and Qt changes the local settings when using debug but only if it blocked before (actually using IPython, which PyCharm debugger uses in background)
