### ISSUE TITLE
Installation using conda forge missing some libraries

### ISSUE THREAD

**Issue by RouvierT** [pyomeca/bioptim#352]
Hello,

I tried installing bioptim on Windows 10, Python 3.9.4 using the conda-forge channel in Minconda3 (Which is the easiest way to install bioptim from the git's ReadMe), but when I tried to launch the pendulum example, I had an error stating that the "graphviz" library was not found.

I then tried installing bioptim on the very same configuration but using the environment.yml file found in bioptim-master, parametered the environment the same way as the first time, and ran pendulum.py, which was successfull.

Is it possible that the conda-forge repository is not up to date ?

Cheers,
Théo

**Comment by mickaelbegon** [comment]
Try 
conda install -c conda-forge graphviz
the readme will be updated shortly

**Comment by pariterre** [comment]
Hi @RouvierT 
It is surprising to me that the anaconda version requires graphviz, since the version 1.2.1 is prior to the add of the graph... I am pushing a release very soon anyway, so this should resolve the problem

Please note that the dependency to install is not `graphviz` but `python-graphviz`. So the install line should read: 
```
conda install -cconda-forge python-graphviz
```

Thanks for reporting!

**Comment by RouvierT** [comment]
Thank you for looking into it !

What I ended doing was running :
`conda env create -f environment.yml`
pointing to the environment.yml file at the root of the downloaded bioptim directory, it works wonders !

Cheers
