### ISSUE TITLE
Accessing contact forces during solving

### ISSUE THREAD

**Issue by MennatallahRihan** [pyomeca/bioptim#541]
Hello,

I was wondering if there is a method to access the value of the contact forces while the problem is running. Like including it in my states so I can perform some calculations using those values in the dynamics functions.

Thank you!

**Comment by Ipuch** [comment]
Hi,
Do you want to display the contact forces, or do you want to implement special features based on the contact forces?

**Comment by MennatallahRihan** [comment]
I want to implement features based on the forces

**Comment by Ipuch** [comment]
First, 
Get a look at:  https://github.com/pyomeca/bioptim/blob/master/bioptim/examples/getting_started/custom_dynamics.py
Then, Here is how you can get the forces :

https://github.com/pyomeca/bioptim/blob/dc16e58efa8dde0679ee73a2694cd2c1301e4082/bioptim/dynamics/dynamics_functions.py#L758-L767

Can you provide more information on what is your idea? it would help to provide you guidance.

Regards,

Pierre

**Comment by MennatallahRihan** [comment]
Hello,
I'm working on a model where I calculate the torques required based on some feedback of joint angles and contact forces.
So the idea is I can create a custom dynamics function and use the line cs.getForce().to_mx() to access the force?  Can I add them to my states in the problem too?

**Comment by Ipuch** [comment]
It is possible to define them as a state.

But, these contact forces are handled through a differential algebraic equation computed by rbdl. They are functions of q, qdot so it would be dangerous to define them as decision variables because they are explicitly and already defined by q and qdot.

If you have a reference for your idea, maybe I can get a look. Or if you could provide a draft of the function you want to implement, I could help you with that.

Regards,

Pierre
