### ISSUE TITLE
Version 3.0.0 creating bioptim 2.3.0 on channel pypi

### ISSUE THREAD

**Issue by tiagocoelhoma** [pyomeca/bioptim#601]
Hi!
I downloaded bioptim after the new release v3.0.0 today through "conda create --name bioptim -c conda-forge bioptim" and the following packages were created, including bioptim v2.3.0 on pypi channel.

Name                    Version                   Build  Channel
aiohttp                   3.8.3           py311ha68e1ae_1    conda-forge
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
aom                       3.5.0                h63175ca_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
attrs                     22.2.0             pyh71513ae_0    conda-forge
bioptim                   2.3.0                    pypi_0    pypi
....

I tested on Windows 10 and got same issue on Ubuntu.

Thanks!
Tiago Coelho Magalhães

**Comment by Ipuch** [comment]
Hi,
Thank you for trying bioptim !

I've tested this morning. It worked perfectely for me. Here is how I've done:

![image](https://user-images.githubusercontent.com/40755537/214053135-5fa985d2-648f-4f96-a50e-2dada6f31f87.png)

Let me know if you have any clue. Which version of python do you use? 

Regards,

Pierre

**Comment by pariterre** [comment]
Dear @tiagocoelhoma 

It is possible that PyPi channel is not up-to-date as I do not actively do anything related to that. It was automatically added months ago (and actually did not work for months) up to the point it did work (I did not know that myself, I had a look just prior to answering). If you do not need PyPi. I'd suggest to install in two go, as @Ipuch did. That is:
```bash
conda create --name bioptim 
conda activate bioptim
conda install -c conda-forge bioptim
```
rather that
```bash
conda create --name bioptim -c conda-forge bioptim
```
I hope this will help

**Comment by tiagocoelhoma** [comment]
Hi everyone, 

thank you for the answers!
Unfortunately, It did not work for me. I will try to find a solution later.

Here you can find the log
[bioptimTextFile.txt](https://github.com/pyomeca/bioptim/files/10480516/bioptimTextFile.txt)

**Comment by pariterre** [comment]
It seems that you have channel pypi added to your default list and/or bioptim was previously installed using PyPi channel and it therefore uses the cached version (instead of downloading it).
You can try these two things:
1. Force conda to use 3.0.0 version (`conda install -cconda-forge bioptim=3.0.0`) 
2. You can delete the cached version (it is in the miniconda folder, which would be `C:\Users\tiago\miniconda3` in your case, then `pkgs`)

If this does not work, make sure you remove PyPi from the default channel (you can see if it is as such using the command `conda info`)

**Comment by pariterre** [comment]
Out of curiosity, I installed it from Windows too, and experience the same thing, I come back when I have a working solution!

**Comment by pariterre** [comment]
Okay it seems that it is a bug from conda list. 
Even though conda list returns that bioptim is 2.3.0, if I actually run python, I get:
```python
import bioptim
print(bioptim.__version__)
    '2.3.1'
```
Which is normal since I forgot to bump the version to 3.0.0 in __version__. That said, it is definitely not 2.3.0 as suggested by conda. 
Moreover, if I do:
```python
bioptim.BioModel
```
it does not crash, but this was added to the 3.0.0 version. I think you have it installed properly

**Comment by pariterre** [comment]
Dear @tiagocoelhoma 
So, we updated all the pyomeca suite to make sure all the version numbers programmatically gotten match the actual release versions in GitHub. It should therefore fix the problem we discussed earlier !
Thanks for giving trying bioptim a try!
