### ISSUE TITLE
Initialization failed since variables are free

### ISSUE THREAD

**Issue by tiagocoelhoma** [pyomeca/bioptim#701]
Hello,

I am currently facing difficulties with free variables in my custom dynamics. Specifically, I need to access a specific value from a pre-defined list, where the index is represented by a variable 't' (time). I would like to know if it is possible to use a variable as an index to access list elements in this manner.
In my implementation, the calculation of dynamics relies on previous time-dependent results, which (in this new approach I am trying) ecessitates accessing specific elements from the list using a variable as the index. I am seeking a workaround or alternative approach to address this issue.

Thank you for your assistance in finding a solution to this challenge.

An error message for example:
`ForwardDyn::init: Initialization failed since variables [t] are free. These symbols occur in the output expressions but you forgot to declare these as inputs. Set option 'allow_free' to allow free variables.`

Best regards,
Tiago.

**Comment by Ipuch** [comment]
Free variables is a classic error message of Casadi.
It means that you try to create a function handle 
Dx/dt = f(x,u) without giving the extra decision variables t

This would require to declare  dynamics functions f(x,u,t).

To leverage this issue what we've done so far with @Kev1CO is to declare dynamics function for each shooting nodes such as

f(x,u,t1) = f1(x,u)
f(x,u,t2) = f2(x,u)

And we created as much as continuity constraint as needed.

Such that x_i+1 - xi - int fi(x,u) dt = 0

To me, there is no way to consider only one dynamic function for every shooting node.

Because time ti are treated differently at each node.

If you get a look at the repo of Kevin we had to implement a custom configure_dynamics_function. 
That's where it is all handled.

If you want me to understand better you message error, please provide the entire message.


@Kev1CO do you see other technical details to precise ? 


@fbailly

**Comment by pariterre** [comment]
Hi @tiagocoelhoma 

Thanks for asking :)

(Just pitching some ideas as I only have 2 minutes left)

We could discuss this further, but I partly disagree with the explaination of @Ipuch . As part of the parameter set, time is indeed sent to the f1(x,u,p) function. That said, I agree with the fact that there is no way to declare one dynamic at each node, You would have to declare X phases of 1 node (instead of a single phase of X nodes) to achieve something like that. However, currently, a phase with a single node won't work. As a workaround, you could declare phases of 2 (or 3, I can't remember) nodes. Then, if you specify these phases to be discontinuous, you can add multinode constraints between the last and first nodes of two consecutive phases that implements your continuity constraint.

(Sorry, I cannot be more specific right now, but I could come back later if needed!)

**Comment by tiagocoelhoma** [comment]
Hello @pariterre

First of all, thank you so much for the attention.

I tried your suggestion these last two days but encountered the same
problem with the initialization:

*RuntimeError: Error in Function::Function for 'ForwardDyn' [MXFunction] at
.../casadi/core/function.cpp:249:*
*.../casadi/core/function_internal.cpp:145: Error calling MXFunction::init
for 'ForwardDyn':*
*.../casadi/core/mx_function.cpp:406: ForwardDyn::init: Initialization
failed since variables [t] are free. These symbols occur in the output
expressions but you forgot to declare these as inputs. Set option
'allow_free' to allow free variables.*

I intended to respond to your answer, but I noticed that it had been
deleted. Could you please clarify if the suggestion was not appropriate or
helpful?

Thank you so much.

Best regards,
Tiago Coelho Magalhaes

Em qua., 5 de jul. de 2023 às 15:41, Pariterre ***@***.***>
escreveu:

**Comment by pariterre** [comment]
Hi @tiagocoelhoma 
I removed my answer as @Ipuch suspect what I said was wrong. 

In order to help you, we need to know the code that generate the error and not just the error itself as they are thousands of ways to generate this error. Could you provide us with a minimal code that generate the error?

Thanks!
